CREATE OR REPLACE PROCEDURE BASKET_ADD_SP(
    p_idproduct IN BB_BASKETITEM.IDPRODUCT%TYPE,
    p_idbasket IN BB_BASKETITEM.IDBASKET%TYPE,
    p_price IN BB_BASKETITEM.PRICE%TYPE,
    p_quantity IN BB_BASKETITEM.QUANTITY%TYPE,
    p_codesize IN BB_BASKETITEM.CODESIZE%TYPE,
    p_codeform IN BB_BASKETITEM.CODEFORM%TYPE
)
IS
BEGIN
    INSERT INTO BB_BASKETITEM (IDPRODUCT, IDBASKET, PRICE, QUANTITY, CODESIZE, CODEFORM)
    VALUES (p_idproduct, p_idbasket, p_price, p_quantity, p_codesize, p_codeform);

    COMMIT;
END BASKET_ADD_SP;
/
